name: Deploy Backend (SAM)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::628837662351:role/oidc-cloudcamp-demo-github-role
  STACK_NAME: cloudcamp-backend
  SAM_ARTIFACT_BUCKET: aws-sam-cli-managed-default-samclisourcebucket-9lljdezra984

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assume AWS role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Scan code with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "backend"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true

      - name: SAM build
        run: sam build --template infrastructure.yaml

      - name: SAM validate
        run: sam validate --template .aws-sam/build/template.yaml --lint

      - name: SAM deploy
        run: |
          sam deploy \
            --stack-name "${STACK_NAME}" \
            --region "${AWS_REGION}" \
            --s3-bucket "${SAM_ARTIFACT_BUCKET}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              AdminEmail="${{ vars.ADMIN_EMAIL || 'alzate901@gmail.com' }}" \
              SenderEmail="${{ vars.SENDER_EMAIL || 'alzate901@gmail.com' }}" \
              SesIdentityDomain="${{ vars.SES_IDENTITY_EMAIL || 'alzate901@gmail.com' }}" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
